### PR TITLE
PR9m

### LINKED ISSUE #1: Merge work from external branch and fix
Work has been advance in this branch. Please merge it to this project. It is not building successfully. Seems like some tests have not been implemented. Please fix

```
Tests in error: 
 VerifyCoreTests.rootInstancecontainsFileFeatures:170 » MissingResource Can't f...
 VerifyCoreTests.rootInstancecontainsGMLJP2fileInternalRefToXMLBox:290 » MissingResource
 VerifyCoreTests.rootInstancecontainsGMLJP2fileJPXJP2Compatible:230 » MissingResource
 VerifyCoreTests.rootInstancecontainsGMLJP2fileJp2OtherOuterBox:250 » MissingResource
 VerifyCoreTests.rootInstancecontainsGMLJP2fileJp2OuterBox:240 » MissingResource
 VerifyCoreTests.rootInstancecontainsGMLJP2fileXMLSignaledCorrectly:220 » MissingResource
 VerifyCoreTests.rootInstancecontainsGmlcovCoverageContainer:150 » MissingResource
 VerifyCoreTests.rootInstancecontainsInternalRefToCodestream:300 » MissingResource

Tests run: 50, Failures: 17, Errors: 8, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.498 s
[INFO] Finished at: 2016-03-03T16:43:33-05:00
[INFO] Final Memory: 26M/317M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project ets-gmljpx20: There are test failures.
```

https://github.com/AlbertoSN/GMLJP-v2

### PR DESCRIPTION
**Pull request by AlbertoSN**
Fixes #1

### CODE REVIEW

**Comment by bermud** [comment]
This pull request is not building. @keshav-nangare, please verify.

**Comment by bermud** [comment]
@keshav-nangare, please verify this PR

**Comment by keshavnangare** [comment]
I have tried to build the PR9m branch  but still it is not building and some tests are failing.

The test are failed due to undefined namespaces.

**Comment by AlbertoSN** [comment]
Can you put result here please?

**Comment by keshavnangare** [comment]
Here is the output with error while building with the maven:

[gmljpx_maven_output.txt](https://github.com/opengeospatial/ets-gmljpx20/files/578870/gmljpx_maven_output.txt)

**Comment by keshavnangare** [comment]
The test are failing due to the undefined prefix.

`VerifyCoreTests.rootInstancecontainsCRSdeclaredUsingURIs:80 com.sun.org.apache.xpath.internal.domapi.XPathStylesheetDOM3Exception: Prefix must resol
e to a namespace: RectifiedGrid`

This is one of the test exception, if you observed the test "containsCRSdeclaredUsingURIs" from the CoreTests.java, there is prefix "//RectifiedGrid:*" is evaluated.

But "//RectifiedGrid:*" is not defined as prefix in the data file (test/resorces/jp2/romagmljp2-collection2-rreq7.jp2) so it is not resolved.

We need define the correct prefix to get proper value from the data file.

Similarly we need to change other prefix too.

**Comment by bermud** [comment]
@AlbertoSN, can you please help us figuring out the prefixes issues?

**Comment by dstenger** [comment]
@AlbertoSN This branch has merge conflicts. Can you please resolve those? If you need any help with that, please let us know.

**Comment by lgoltz** [comment]
Remaining work will be done in #6 and #10.

**Pull request closed without merging**
