### PR TITLE
Adapted and added tests to - v21 OGC 08-085r8

### PR DESCRIPTION
**Pull request by alunacob**
I have worked on implementing the new Test Cases and updating the references to the latest revision.

Could someone take a look at it?

Thank You

### CODE REVIEW

**Comment by EmDevys** [comment]
Hi
I am happy to help, as far as I can.
Just one thing to clarify what I may do/ not do, I have no development facility installed on my laptop (and still confined at home – work at home). In addition, my development capabilities are now very limited, and my knowledge of Java is now at beginner level …
Having said that, I know the GMLJP2 v2.1 spec. quite well, as well as its ATS and the corresponding requirements.
One key thing is to add testing of referenceableGridCoverage extension (v1.1.1, cf. http://docs.opengeospatial.org/is/16-083r3/16-083r3.html) I am unsure whether an OGC ETS is available for this one (or under development), but Eric Hirschorn, the author of this extension for referenceableGridCoverage, is for sure able to provide an answer. Eric might as well be interested in the extension of the GMLJP2 v2.0 ETS to the version 2.1.

Cheers

Emmanuel Devys
IGN Département Normalisation et référentiels projets| Service des Projets et Prestations
direction des programmes et de l’appui aux politiques publiques
T +33 (0) 1 43 98 85 75
ign.fr<http://www.ign.fr/> – geoportail.gouv.fr




De : alunacob [mailto:notifications@github.com]
Envoyé : jeudi 21 mai 2020 13:05
À : opengeospatial/ets-gmljpx20
Cc : Subscribed
Objet : [opengeospatial/ets-gmljpx20] Adapted and added tests to - v21 OGC 08-085r8 (#36)


I have worked on implementing the new Test Cases and updating the references to the latest revision.

Could someone take a look at it?

Thank You

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/opengeospatial/ets-gmljpx20/pull/36

Commit Summary

  *   Fixed and added tests compliance with Core Conformance Test Class of v2.1
  *   updated to v21 OGC 08-085r8

File Changes

  *   M README.adoc<https://github.com/opengeospatial/ets-gmljpx20/pull/36/files#diff-7bd4a925c695c2eb0eced3872b9b965f> (4)
  *   M src/main/java/org/opengis/cite/gmljpx20/ErrorMessageKeys.java<https://github.com/opengeospatial/ets-gmljpx20/pull/36/files#diff-e56bb2755ddf50527e39216d899e3a75> (3)
  *   M src/main/java/org/opengis/cite/gmljpx20/core/CoreTests.java<https://github.com/opengeospatial/ets-gmljpx20/pull/36/files#diff-78e9df46ba001e2e2c16a5f866bf05ab> (348)

Patch Links:

  *   https://github.com/opengeospatial/ets-gmljpx20/pull/36.patch
  *   https://github.com/opengeospatial/ets-gmljpx20/pull/36.diff

**Comment by ghobona** [comment]
@alunacob Thanks for the Pull Request and the excellent work.

Since the ETS currently supports GMLJP2 v2.0, the edits should not replace but instead should add to the existing test suite in order to support GMLJP2 v2.1.

@dstenger how about if @alunacob changes the edits such that for tests that are in both v2.0 and v2.1, the description looks something like `@Test(description = "OGC 08-085r4, A.1.7 and OGC 08-085r8, A.1.8")`?

@EmDevys Thanks for the feedback. We'll let you and Eric know when the changes are ready for review.

**Comment by alunacob** [comment]
> @alunacob Thanks for the Pull Request and the excellent work.
> 
> Since the ETS currently supports GMLJP2 v2.0, the edits should not replace but instead should add to the existing test suite in order to support GMLJP2 v2.1.
> 
> @dstenger how about if @alunacob changes the edits such that for tests that are in both v2.0 and v2.1, the description looks something like `@Test(description = "OGC 08-085r4, A.1.7 and OGC 08-085r8, A.1.8")`?
> 
> @EmDevys Thanks for the feedback. We'll let you and Eric know when the changes are ready for review.

Would be happy to implement the suggested approach. I wait for @dstenger confirmation.

@EmDevys, In addition, I found requirement 5 especially hard to implement: https://docs.opengeospatial.org/is/08-085r8/08-085r8.html#14 

Since it refers to another standard and also A1.5 validation criteria is to my perception not very specific. I would greatly appreaciate some hints on that.

**Comment by dstenger** [comment]
@alunacob and @ghobona, Yes, I agree and am also in favor of the proposed approach that the test suite supports both versions (just one interface).

@ghobona This also means that we should rename the GitHub repository, update the documentation, etc. Maybe, we can create a new issue for that as soon as the implementation is finished.

**Comment by ghobona** [comment]
I discussed this with @dstenger today (2020-06-02).

@alunacob Yes, please proceed with updating the Pull Request as suggested in Comment  https://github.com/opengeospatial/ets-gmljpx20/pull/36#issuecomment-635125131

**Comment by alunacob** [comment]
Dear all, I have made the suggested changes.

Please, check if it is fine now.

Thank You!

**Review by ghobona — APPROVED** [review]
Reviewed the changes and tested on sample GMLJP2 v2 files.

**Comment by ghobona** [comment]
@dstenger I'm happy with the changes. Shall I proceed to merge the PR?

**Comment by dstenger** [comment]
@ghobona
Sure, you can merge this pull request.
I already set the milestone to 1.1.

**Pull request merged**
